### ISSUE TITLE
自定义

### ISSUE THREAD

**Issue by dong136279559** [OpenFeyn/KafkaRefresh#27]
是否能提供一个类,或者scrollview的方法,监听滚动,自己定制view,或者不只在tableview的headerView上增加,支持使用者自己设置.

**Comment by OpenFeyn** [comment]
继承 KafkaHeadRefreshControl  KafkaFootRefreshControl

- (void)kafkaDidScrollWithProgress:(CGFloat)progress max:(const CGFloat)max
{
   //进度回调
}

- (void)kafkaRefreshStateDidChange:(KafkaRefreshState)state
{
   [super kafkaRefreshStateDidChange:state];
}

**Comment by OpenFeyn** [comment]
继承 KafkaHeadRefreshControl  KafkaFootRefreshControl

- (void)kafkaDidScrollWithProgress:(CGFloat)progress max:(const CGFloat)max
{
   //进度回调
}

- (void)kafkaRefreshStateDidChange:(KafkaRefreshState)state
{
   [super kafkaRefreshStateDidChange:state];
}

**Comment by OpenFeyn** [comment]
是值自定义吗？
