### ISSUE TITLE
如果设置了contentInset刷新控件显示位置不对

### ISSUE THREAD

**Issue by wwdc14** [OpenFeyn/KafkaRefresh#28]
如图显示：

![IMG_1AADD62A332D-1](https://s1.ax1x.com/2018/05/03/Ctm0AS.jpg)
![IMG_47535179C578-1](https://s1.ax1x.com/2018/05/03/CtmBtg.jpg)

**Comment by OpenFeyn** [comment]
并非位置不对，KafkaRefresh内部实现逻辑即如此。
你的页面有其他设计思路去避开这类问题。
自行调整即可
