### ISSUE TITLE
Can I create child of KafkaRefreshControl that always will be visible?

### ISSUE THREAD

**Issue by chapayGhub** [OpenFeyn/KafkaRefresh#33]
I need to show table footer view (with copyright text) always in a bottom of tableview
The problem when no data in tableview and standart footer showed in a top

Can KafkaRefresh help me?

**Comment by OpenFeyn** [comment]
Yes.
you can call method `- (void)endRefreshingAndNoLongerRefreshingWithAlertText:(NSString *)text` when no data, no need to create child of KafkaRefreshControl.

**Comment by OpenFeyn** [comment]
if you create child of KafkaRefreshControl, you need inherit KafkaFootRefreshControl,  afterwards,overiding setter method
```objective-c
- (void)setRefreshState:(KafkaRefreshState)refreshState{
  [super setRefreshState:refreshState];
  self.alpha = 1.0;
}
```
that's ok.
