### ISSUE TITLE
self.scrollView.isDragging 在ios10 ios11系统中并且生效导致下拉刷新加载条偏移

### ISSUE THREAD

**Issue by WSFeng** [OpenFeyn/KafkaRefresh#39]
- iOS版本；在ios10 ios11
- KafkaRefresh版本:  1.2.3；
- self.scrollView.isDragging 在ios10 ios11系统中并且生效导致下拉刷新加载条偏移

demo请使用自定义scrollView测试,不要使用系统的那个scrollViewVc来写,可能你就能发现问题

**Comment by OpenFeyn** [comment]
已自定义ScrollView集成刷新，未发现加载条偏移。

“self.scrollView.isDragging 在ios10 ios11系统中并且生效导致下拉刷新加载条偏移”这句，请分两句描述。
