### ISSUE TITLE
UICollectionView 在数据无法填充屏幕时 刷新和加载都触发不了。

### ISSUE THREAD

**Issue by Ludy2015** [OpenFeyn/KafkaRefresh#40]
提交bug前:

- 请定位该bug是否由自身代码引发，当该bug模糊不清时，您应该继续思索；
- 如果您发现该bug由KafkaRefresh引发，且您能修改源码解决，欢迎您提交解决方案或提交一个request，在此先表示感谢。

提交bug必须包含下列要点:

- iOS版本；
- KafkaRefresh版本（可查看cocoapods中提示的版本信息）；
- 请您务必给出详细的重现步骤。

**Comment by OpenFeyn** [comment]
收到
今明两天将会更新版本至1.3.0
谢谢

**Comment by OpenFeyn** [comment]
设置collectionView.alwaysBounceVertical = YES;即可
collectionView默认bounce为NO；
