### ISSUE TITLE
主动下拉刷新问题

### ISSUE THREAD

**Issue by lilinxuan** [OpenFeyn/KafkaRefresh#42]
添加完tableview下拉刷新之后调用 主动下拉刷新 页面顶部会多出30左右的空

**Comment by lilinxuan** [comment]
主动下拉刷新 延时执行就没问题

**Comment by lilinxuan** [comment]
代码如下。进页面 顶部就会空出来一部分。。。
[self.tableV bindGlobalStyleForHeadRefreshHandler:^{   
    }];
     [self.tableV.headRefreshControl beginRefreshing];

**Comment by lilinxuan** [comment]
dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(0.3 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        [self.tableV.headRefreshControl beginRefreshing];
    });

延时执行就没问题了

**Comment by OpenFeyn** [comment]
请按格式New Issue，版本号，机型，重现步骤。
