### ISSUE TITLE
跪求Swift版本，特别喜欢这个刷新控件

### ISSUE THREAD

**Issue by 29745560** [OpenFeyn/KafkaRefresh#43]
提交bug前:

- 请定位该bug是否由自身代码引发，当该bug模糊不清时，您应该继续思索；
- 如果您发现该bug由KafkaRefresh引发，且您能修改源码解决，欢迎您提交解决方案或提交一个request，在此先表示感谢。

提交bug必须包含下列要点:

- iOS版本；
- KafkaRefresh版本（可查看cocoapods中提示的版本信息）；
- 请您务必给出详细的重现步骤。

**Comment by OpenFeyn** [comment]
KafkaRefresh 接下来将重构更新至2.0版本，在动画效果、接口及整体的代码设计做处较大改动，之后才会发布Swift版。

**Comment by BinBear** [comment]
@OpenFeyn 2.0版本大概啥时候更新呢
