### ISSUE TITLE
KafkaRefreshStyleReplicatorDot 不居中

### ISSUE THREAD

**Issue by fuzhenjin** [OpenFeyn/KafkaRefresh#45]
提交bug前:

- 请定位该bug是否由自身代码引发，当该bug模糊不清时，您应该继续思索；
- 如果您发现该bug由KafkaRefresh引发，且您能修改源码解决，欢迎您提交解决方案或提交一个request，在此先表示感谢。

提交bug必须包含下列要点:

- iOS版本；
- KafkaRefresh版本（可查看cocoapods中提示的版本信息）；
- 请您务必给出详细的重现步骤。

**Comment by OpenFeyn** [comment]
谢谢。
1.3.0修复。
已更新
