### ISSUE TITLE
bug : in a horizontal collection view the pull to refresh triggered from left to right not from top to bottom

### ISSUE THREAD

**Issue by alouanemed** [OpenFeyn/KafkaRefresh#46]
提交bug前:

- 请定位该bug是否由自身代码引发，当该bug模糊不清时，您应该继续思索；
- 如果您发现该bug由KafkaRefresh引发，且您能修改源码解决，欢迎您提交解决方案或提交一个request，在此先表示感谢。

提交bug必须包含下列要点:

- iOS版本；12
- KafkaRefresh版本（可查看cocoapods中提示的版本信息）； latest
- 请您务必给出详细的重现步骤。

When using a horizontal collectionview with empty data, the refresh get triggered if pulled from left to right.

**Comment by OpenFeyn** [comment]
hello,
kafkarefresh is not suitable for collectionview when scrollDirection is horizontal.

**Comment by alouanemed** [comment]
aha I see, do you recommend any alternatives? Thanks.

**Comment by alouanemed** [comment]
Thanks :)
