### ISSUE TITLE
swift 方式一初始化 header refresh control 为nil 

### ISSUE THREAD

**Issue by SpectatorNan** [OpenFeyn/KafkaRefresh#47]
提交bug前:

- 请定位该bug是否由自身代码引发，当该bug模糊不清时，您应该继续思索；
- 如果您发现该bug由KafkaRefresh引发，且您能修改源码解决，欢迎您提交解决方案或提交一个request，在此先表示感谢。

提交bug必须包含下列要点:

- iOS版本；
- KafkaRefresh版本（可查看cocoapods中提示的版本信息）；
- 请您务必给出详细的重现步骤。

![image](https://user-images.githubusercontent.com/13959374/51094348-0dec8780-17e7-11e9-902d-bab3f3bd734d.png)

**Comment by OpenFeyn** [comment]
//kafkarefresh 下拉刷新
tableView.bindGlobalStyle(forHeadRefreshHandler: .....)
而不是
tableView.bindGlobalStyle(forFootRefreshHandler: .....)

**Comment by SpectatorNan** [comment]
O__O "…   copy+手敲的时候粗心了 不好意思
