### ISSUE TITLE
Swift 使用自定义代理无效

### ISSUE THREAD

**Issue by Ccmi** [OpenFeyn/KafkaRefresh#48]
- iOS版本；最新
- KafkaRefresh版本：最新
![image](https://user-images.githubusercontent.com/17047142/51232624-6320c880-19a2-11e9-8581-1227061c8750.png)

**Comment by OpenFeyn** [comment]
1.是如何绑定到<scroll view>上的？
```objc
CustomHeadControl *c = [[CustomHeadControl alloc] init];
c.refreshHandler = ^{
        //.....
};
self.tableView.headRefreshControl = c;
```
2.直接查看 ～ ./KafkaRefresh/UIKit/HeadKit目录下任意一种Head的实现，做对比。

**Comment by Ccmi** [comment]
先赋值闭包给 tableView 是可以的；
这样的不行：
CustomHeadControl *c = [[CustomHeadControl alloc] init];
self.tableView.headRefreshControl = c;
c.refreshHandler = ^{
        //.....
};

**Comment by OpenFeyn** [comment]
即使闭包后赋值，本地测试未发现问题。
下载demo，修改成你的方式运行，即可测试到。

**Comment by OpenFeyn** [comment]
```objc
CustomHeadControl *c = [[CustomHeadControl alloc] init];
self.tableView.headRefreshControl = c;
c.refreshHandler = ^{
        dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(2. * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
            [weakSelf.tableView.headRefreshControl endRefreshing];
     });
};
```

**Comment by Ccmi** [comment]
抱歉，是我自己的问题；😰
