### ISSUE TITLE
在collectionView里，显示偏右

### ISSUE THREAD

**Issue by libern** [OpenFeyn/KafkaRefresh#49]
iPhone X, 最新kafkaRefresh版本，iOS12

当想要集成到这个里面时：https://github.com/SoySauceLab/CollectionKit

都能正常显示，但是，显示出现了不居中（偏右）

![image](https://user-images.githubusercontent.com/1830640/53296752-d9400700-384d-11e9-896a-6429984d0e8a.png)

**Comment by libern** [comment]
![image](https://user-images.githubusercontent.com/1830640/53296834-0fca5180-384f-11e9-92f3-907660b6fb43.png)

**Comment by masuhara** [comment]
@libern 
Same here. How do you fix it?

**Comment by masuhara** [comment]
@OpenFeyn 
Thanks for the great lib.
I installed ver 1.4.0 but this issue is not fixed for me.

triangle dots type indicator / on CollectionView

Thanks

**Comment by OpenFeyn** [comment]
please tell me the steps to reproduce.  i test it, the demo without problem. Is CollectionView over-customized?

**Comment by libern** [comment]
You shouldn't set any contentInset to the CollectionView, Otherwise, this lib will not working expected.

**Comment by AL-bruce** [comment]
UICollectionView set contentInset will show the mistake

**Comment by AL-bruce** [comment]
> iPhone X, 最新kafkaRefresh版本，iOS12
> 
> 当想要集成到这个里面时：https://github.com/SoySauceLab/CollectionKit
> 
> 都能正常显示，但是，显示出现了不居中（偏右）
> 
> ![image](https://user-images.githubusercontent.com/1830640/53296752-d9400700-384d-11e9-896a-6429984d0e8a.png)

请问是改了源码还是其他方式居中的呢
