### ISSUE TITLE
Refresh icons are slightly off the center to the right

### ISSUE THREAD

**Issue by masuhara** [OpenFeyn/KafkaRefresh#50]
Thanks for this great lib.
謝謝你的美好事物

I find that a refresh icon is slightly off the center to the right.
圖標略微偏離右側中心

Same issue is here.
同樣的問題已經解決了
https://github.com/OpenFeyn/KafkaRefresh/issues/49

Is this issue fixed already?
這個問題已經解決了嗎？

If someone know how to fix it, please tell me how to fix it.
如果能告訴我是否有解決方案，我很高興

Thanks
謝謝

**Comment by masuhara** [comment]
This occurs in CollectionView

**Comment by OpenFeyn** [comment]
Hi ! Please tell me the version number you are using. Please update to the latest version and retry it. Local test has not found the problem yet

**Comment by OpenFeyn** [comment]
If you find that the problem persists in the latest version, I will solve the problem today, thank you for your feedback.
問題が最新バージョンで解決しないことがわかった場合は、今日問題を解決します。フィードバックをいただきありがとうございます。

**Comment by OpenFeyn** [comment]
thank you for your feedback. This problem occurs when using KafkaRefreshStyleReplicatorAllen or KafkaRefreshStyleReplicatorArc. I will fix the problem today, please wait for the update to complete. Thanks again for the feedback.
ご意見ありがとうございました。 この問題は、KafkaRefreshStyleReplicatorAllenまたはKafkaRefreshStyleReplicatorArcを使用しているときに発生します。 私は今日問題を解決します、アップデートが完了するのを待ってください。 ご意見ありがとうございました。
