### ISSUE TITLE
scroll bounds 异常

### ISSUE THREAD

**Issue by SpectatorNan** [OpenFeyn/KafkaRefresh#54]
提交bug前:

- 请定位该bug是否由自身代码引发，当该bug模糊不清时，您应该继续思索；
- 如果您发现该bug由KafkaRefresh引发，且您能修改源码解决，欢迎您提交解决方案或提交一个request，在此先表示感谢。

提交bug必须包含下列要点:

- iOS版本；12.2
- KafkaRefresh版本（可查看cocoapods中提示的版本信息）；  1.4.0
- 请您务必给出详细的重现步骤。

![image](https://user-images.githubusercontent.com/13959374/57093315-1f2eb500-6d40-11e9-8341-0acffc53b0f3.png)
![image](https://user-images.githubusercontent.com/13959374/57093392-57ce8e80-6d40-11e9-9184-5f7c27f4001b.png)
![image](https://user-images.githubusercontent.com/13959374/57093430-72086c80-6d40-11e9-830b-14924bcdb982.png)

uiscrollview  顶部贴着屏幕， 添加headerControl ，顶部会被占用45 的高度，contentview的frame通过reveal查看 x y 均为 0，headerControl 的frame为 0，-45，375，45。  代码如上。 可判断这个空白不是 scroll 自动调整高度的64

![image](https://user-images.githubusercontent.com/13959374/57097813-43dc5a00-6d4b-11e9-8637-11049a6f0dad.png)

**Comment by OpenFeyn** [comment]
是被遮挡还是什么，origin=0,-45 有问题？

**Comment by SpectatorNan** [comment]
![image](https://user-images.githubusercontent.com/13959374/57120723-c6920300-6da5-11e9-96ac-ef9ca90fdcbe.png)
这个是预期的样子
![image](https://user-images.githubusercontent.com/13959374/57120744-f5a87480-6da5-11e9-91cd-0f4a8f63bf16.png)
产生顶部留白  意思是 下拉之后没有弹回去，顶部留有一个45高度的空白

**Comment by OpenFeyn** [comment]
本地测试没有重现
```objective-c


- (void)viewDidLoad {
    [super viewDidLoad];
    
    if (@available(iOS 11, *)) {
        self.scrollView.contentInsetAdjustmentBehavior = UIApplicationBackgroundFetchIntervalNever;
    } else {
        self.automaticallyAdjustsScrollViewInsets = false;
    } 
    [self.navigationController.navigationBar setBackgroundImage:[UIImage new] forBarMetrics:(UIBarMetricsDefault)];
    
    [self.view addSubview:self.scrollView];
    self.scrollView.backgroundColor = [UIColor whiteColor];
    self.scrollView.frame = CGRectMake(0, 0, self.view.bounds.size.width, self.view.bounds.size.height);
    self.scrollView.contentSize = CGSizeMake(self.view.bounds.size.width, self.view.bounds.size.height*1.5);
    UIView *contentView = [UIView new];
    contentView.frame = CGRectMake(0, 0, self.view.bounds.size.width, self.view.bounds.size.height*1.5);
    contentView.backgroundColor = [UIColor blueColor];
    [self.scrollView addSubview:contentView];
    
    KafkaRefreshHandler headBlock = ^(void){
        dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(3 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
            [self.scrollView.headRefreshControl endRefreshing];
        });
    };
    
    [self.scrollView bindHeadRefreshHandler:headBlock themeColor:[UIColor redColor] refreshStyle:_style];
}

- (UIScrollView *)scrollView {
    if (!_scrollView) {
        _scrollView = [UIScrollView new];
    }
    return _scrollView;
}

```

**Comment by SpectatorNan** [comment]
貌似找到原因了。我的刷新动画是通过rx绑定的

![image](https://user-images.githubusercontent.com/13959374/57196581-d457ac00-6f90-11e9-8be6-7879565b3d5b.png)
public var isAnimating: Binder<Bool> {
        return Binder(self.base) { refreshControl, active in
            if active {
                refreshControl.beginRefreshing()
            } else {
                refreshControl.endRefreshing()
            }
        }
    }

![image](https://user-images.githubusercontent.com/13959374/57196590-e5a0b880-6f90-11e9-9549-2ec2ca3e90f4.png)
使用普通方式结束刷新正常

**Comment by SpectatorNan** [comment]
可能是在数据绑定的时候产生了什么影响， 导致headrefresh暴露出来了，将原本的view给顶下来，从而产生了空白。

**Comment by OpenFeyn** [comment]
安好！
