### ISSUE TITLE
关于第一次调用 endRefreshingAndNoLongerRefreshingWithAlertText 时的疑问

### ISSUE THREAD

**Issue by Ccmi** [OpenFeyn/KafkaRefresh#55]
- iOS版本：12.3.1
- 最新 Github Demo代码
- 当我在 viewdidload 最后一行调用 endRefreshingAndNoLongerRefreshingWithAlertText 时，当前列表还可以继续上拉加载；请问这是正常的吗？因为我在 swift 里面网络请求上拉加载时第一次调用此方法也会出现还可以上拉加载；
![image](https://user-images.githubusercontent.com/17047142/58850780-79fe5800-86c2-11e9-88f5-41f03b9c775a.png)

**Comment by Ccmi** [comment]
发现原因所在了，由于我第一次请求到数据就可能是最后一页，但是在调用此方法时会判断 footer 的刷新状态，而不执行此方法；请问有什么方式可以直接让 footer 在没有进行刷新的情况下设置为没有更多数据吗？
![image](https://user-images.githubusercontent.com/17047142/58851063-d6ae4280-86c3-11e9-95f8-d17ff26f3960.png)

**Comment by Ccmi** [comment]
另外有一个问题，就是没有更多数据的底部 label 如何去掉背景颜色呢？

**Comment by OpenFeyn** [comment]
1、1.4.5版本已经支持。2、背景色请查看文档

**Comment by Ccmi** [comment]
好的，非常感谢；

**Comment by OpenFeyn** [comment]
Vpn断了，还在修复，请等待pod
