### ISSUE TITLE
Bundle arrow image is nil

### ISSUE THREAD

**Issue by wwwang89** [OpenFeyn/KafkaRefresh#56]
- (UIImageView *)arrowImgV{
	if (!_arrowImgV) {
		NSString *path = [[NSBundle mainBundle] pathForResource:@"Image" ofType:@"bundle"];
		NSString *urlString = [path stringByAppendingPathComponent:@"arrow48.png"];
		UIImage *image = [UIImage imageWithContentsOfFile:urlString];
		_arrowImgV = [[UIImageView alloc] initWithImage:image];
		_arrowImgV.layer.anchorPoint = CGPointMake(0.5, 0);
	}
	return _arrowImgV;
}

hi ,thanks for so great refresh Lib.
when  I. use it in KafkaRefreshStyleAnimatableArrow style ,the arrowImage return nil ,there sth went wrong ? I guess the path you get is wrong !

**Comment by wwwang89** [comment]
I use it in cocoa pods,your demo is ok !

**Comment by OpenFeyn** [comment]
使用这个样式时箭头图标不显示吗？还是你想使用我bundle里的图标？

**Comment by wwwang89** [comment]
[self bindHeadRefreshHandler:^{
            // 下拉刷新
            
        } themeColor:nil refreshStyle:KafkaRefreshStyleAnimatableArrow];


here，use KafkaRefreshStyleAnimatableArrow style，but  the arrow is not shown in UI ！ I guess the path you get is wrong !

**Comment by OpenFeyn** [comment]
今晚会更新至1.5.0后修复

**Comment by wwwang89** [comment]
oh I'm sorry ,the version in pods is still 1.4.0. Could you update the pod rep synchronously ？

**Comment by OpenFeyn** [comment]
早已更新至1.4.7

**Comment by wwwang89** [comment]
I'm sorry ,u can use  "pod search KafkaRefresh",
and the below:

-> KafkaRefresh (1.4.0)
   Highly scalable, custom, multi-style refresh framework.
   pod 'KafkaRefresh', '~> 1.4.0'
   - Homepage: https://github.com/xorshine/KafkaRefresh
   - Source:   https://github.com/xorshine/KafkaRefresh.git
   - Versions: 1.4.0, 1.3.0, 1.2.3, 1.2.1, 1.2.0, 1.1.0, 1.0.2, 1.0.1, 1.0.0,
   0.9.9, 0.9.8, 0.9.7, 0.9.6, 0.9.5, 0.9.4, 0.9.3, 0.9.2, 0.9.1, 0.9.0, 0.8.9,
   0.8.8, 0.8.7, 0.8.6, 0.8.5, 0.8.4, 0.8.3, 0.8.2, 0.8.0, 0.7.5, 0.7.4, 0.7.3,
   0.7.0, 0.6.9, 0.6.0, 0.5.9 [master repo]
   - Subspecs:
     - KafkaRefresh/Category (1.4.0)
     - KafkaRefresh/Core (1.4.0)
     - KafkaRefresh/Configuration (1.4.0)
     - KafkaRefresh/Default (1.4.0)
     - KafkaRefresh/Style (1.4.0)
     - KafkaRefresh/UIKit (1.4.0)
     - KafkaRefresh/UIKit/HeadKit (1.4.0)
     - KafkaRefresh/UIKit/FootKit (1.4.0)
     - KafkaRefresh/UIKit/LayerKit (1.4.0)

**Comment by OpenFeyn** [comment]
-> KafkaRefresh (1.4.7)
   Highly scalable, custom, multi-style refresh framework.
   pod 'KafkaRefresh', '~> 1.4.7'
   - Homepage: https://github.com/xorshine/KafkaRefresh
   - Source:   https://github.com/xorshine/KafkaRefresh.git
   - Versions: 1.4.7, 1.4.6, 1.4.5, 1.4.0, 1.3.0, 1.2.3, 1.2.1, 1.2.0, 1.1.0,
   1.0.2, 1.0.1, 1.0.0, 0.9.9, 0.9.8, 0.9.7, 0.9.6, 0.9.5, 0.9.4, 0.9.3, 0.9.2,
   0.9.1, 0.9.0, 0.8.9, 0.8.8, 0.8.7, 0.8.6, 0.8.5, 0.8.4, 0.8.3, 0.8.2, 0.8.0,
   0.7.5, 0.7.4, 0.7.3, 0.7.0, 0.6.9, 0.6.0, 0.5.9 [master repo]
   - Subspecs:
     - KafkaRefresh/Category (1.4.7)
     - KafkaRefresh/Core (1.4.7)
     - KafkaRefresh/Configuration (1.4.7)
     - KafkaRefresh/Default (1.4.7)
     - KafkaRefresh/Style (1.4.7)
     - KafkaRefresh/UIKit (1.4.7)
     - KafkaRefresh/UIKit/HeadKit (1.4.7)
     - KafkaRefresh/UIKit/FootKit (1.4.7)
     - KafkaRefresh/UIKit/LayerKit (1.4.7)

**Comment by OpenFeyn** [comment]
指定podfile文件不小于1.4.7版本进行update
